blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions / Community
    url: https://github.com/helloabhishek2004/AuraMusic/discussions
    about: Ask questions, discuss ideas, and chat with other AuraMusic community members.
